### PR TITLE
Patch stringify_bool for SQLite

### LINKED ISSUE #41: SQLite patch should stringify True and False to 1 and 0
SQLite does not have boolean literals, and both `TRUE` and `FALSE` will cause errors.

I’ll find time to implement this when I can.

### PR DESCRIPTION
**Pull request by uranusjr**
Fix #41

### CODE REVIEW

**Comment by moskytw** [comment]
wonderful

**Comment by uranusjr** [comment]
Super turnover rate. Should this be in the docs? A `versionchanged` tag inside `mosql.sqlite.patch`, maybe?

**Comment by moskytw** [comment]
up to you :P

**Comment by uranusjr** [comment]
#idontcare

**Pull request merged**
